// mapData.js

export const allowedStations = ["Altrincham","Appley Bridge","Ardwick","Ashburys","Ashton-under-Lyne","Atherton","Belle Vue","Blackrod","Bolton","Bramhall","Bredbury","Brinnington","Broadbottom","Bromley Cross","Bryn","Burnage","Castleton","Chassen Road","Cheadle Hulme","Clifton","Daisy Hill","Davenport","Deansgate","Dinting","East Didsbury","Eccles","Fairfield","Farnworth","Flixton","Flowery Field","Gatley","Gathurst","Glazebrook","Glossop","Godley","Gorton","Greenfield","Guide Bridge","Hadfield","Hag Fold","Hale","Hall-i'-th'-Wood","Hattersley","Hazel Grove","Heald Green","Heaton Chapel","Hindley","Horwich Parkway","Humphrey Park","Hyde Central","Hyde North","Ince","Irlam","Kearsley","Levenshulme","Littleborough","Lostock","Manchester Airport","Manchester Oxford Road","Manchester Piccadilly","Manchester Victoria","Marple","Mauldeth Road","Middlewood","Mills Hill","Moorside","Moses Gate","Mossley","Moston","Navigation Road","Newton for Hyde","Orrell","Patricroft","Pemberton","Reddish North","Rochdale","Romiley","Rose Hill","Rose Hill Marple","Ryder Brow","Salford Central","Salford Crescent","Smithy Bridge","Stalybridge","Stockport","Strines","Swinton","Trafford Park","Urmston","Walkden","Westhoughton","Wigan North Western","Wigan Wallgate","Woodley","Woodsmoor"].map(s=>s.toLowerCase());

export const stationAliases = {"trafford palazzo":"barton dock road","robinswood road":"robinswood","rochdale town centre":"rochdale town centre","rochdale railway station":"rochdale railway station","deansgate-castlefield ( deansgate)":"deansgate-castlefield","oldham mumps":"oldham mumps","st peter's square":"st peter's square","st. peter's square":"st peter's square"};

export const tramLines = [
    {name:"Alty-Bury",color:"#00cc00",weight:4,stops:["Altrincham","Navigation Road","Timperley","Brooklands","Sale","Dane Road","Stretford","Old Trafford","Trafford Bar","Cornbrook","Deansgate-Castlefield","St Peter's Square","Market Street","Shudehill","Manchester Victoria","Queens Road","Abraham Moss","Crumpsall","Bowker Vale","Heaton Park","Prestwich","Besses o' th' Barn","Whitefield","Radcliffe","Bury"]},
    {name:"Alty-Picc",color:"purple",weight:3,stops:["Altrincham","Navigation Road","Timperley","Brooklands","Sale","Dane Road","Stretford","Old Trafford","Trafford Bar","Cornbrook","Deansgate-Castlefield","St Peter's Square","Piccadilly Gardens","Manchester Piccadilly"]},
    {name:"Ashton-Eccles",color:"#00BFFF",weight:3,stops:["Ashton-under-Lyne","Ashton West","Ashton Moss","Audenshaw","Droylsden","Cemetery Road","Edge Lane","Clayton Hall","Velopark","Etihad Campus","Holt Town","New Islington","Manchester Piccadilly","Piccadilly Gardens","St Peter's Square","Deansgate-Castlefield","Cornbrook","Pomona","Exchange Quay","Salford Quays","Anchorage","Harbour City","MediaCityUK","Broadway","Langworthy","Weaste","Ladywell","Eccles"]},
    {name:"Bury-Picc",color:"#00cc00",weight:3,stops:["Bury","Radcliffe","Whitefield","Besses o' th' Barn","Prestwich","Heaton Park","Bowker Vale","Crumpsall","Abraham Moss","Queens Road","Manchester Victoria","Shudehill","Market Street","Piccadilly Gardens","Manchester Piccadilly"]},
    {name:"Didsbury-Rochdale",color:"hotpink",weight:3,stops:["East Didsbury","Didsbury Village","West Didsbury","Burton Road","Withington","St Werburgh's Road","Chorlton","Firswood","Trafford Bar","Cornbrook","Deansgate-Castlefield","St Peter's Square","Exchange Square","Manchester Victoria","Monsall","Central Park","Newton Heath and Moston","Failsworth","Hollinwood","South Chadderton","Freehold","Westwood","Oldham King Street","Oldham Central","Oldham Mumps","Derker","Shaw and Crompton","Newhey","Milnrow","Kingsway Business Park","Newbold","Rochdale Railway Station","Rochdale Town Centre"]},
    {name:"Trafford-Deansgate",color:"red",weight:3,stops:["The Trafford Centre","Trafford Palazzo","Parkway","Village","Imperial War Museum","Wharfside","Pomona","Cornbrook","Deansgate-Castlefield"]},
    {name:"Airport-Vic",color:"navy",weight:3,stops:["Manchester Airport","Shadowmoss","Peel Hall","Robinswood Road","Wythenshawe Town Centre","Crossacres","Benchill","Martinscroft","Roundthorn","Baguley","Moor Road","Wythenshawe Park","Northern Moor","Sale Water Park","Barlow Moor Road","St Werburgh's Road","Chorlton","Firswood","Trafford Bar","Cornbrook","Deansgate-Castlefield","St Peter's Square","Market Street","Shudehill","Manchester Victoria"]}
];

export const boroughStops = { 
    "Bolton": ["Blackrod","Bolton","Bromley Cross","Farnworth","Hall-i'-th'-Wood","Horwich Parkway","Kearsley","Lostock","Moses Gate","Westhoughton"], 
    "Bury": ["Besses o' th' Barn","Bury Interchange","Heaton Park","Prestwich","Radcliffe","Whitefield"], 
    "Manchester": ["Abraham Moss","Baguley","Barlow Moor Road","Benchill","Bowker Vale","Burton Road","Central Park","Chorlton","Clayton Hall","Cornbrook","Crossacres","Crumpsall","Deansgate-Castlefield","Didsbury Village","East Didsbury","Etihad Campus","Exchange Square","Holt Town","Manchester Airport","Market Street","Martinscroft","Monsall","Moor Road","New Islington","Newton Heath and Moston","Northern Moor","Peel Hall","Piccadilly","Piccadilly Gardens","Queens Road","Robinswood Road","Roundthorn","Shadowmoss","Shudehill","St. Peter's Square","St Werburgh's Road","Velopark","Victoria","West Didsbury","Withington","Wythenshawe Park","Wythenshawe Town Centre", "Ardwick","Ashburys","Belle Vue","Burnage","Deansgate","Gorton","Levenshulme","Manchester Oxford Road","Mauldeth Road","Moston","Ryder Brow"], 
    "Oldham": ["Derker","Failsworth","Freehold","Hollinwood","Oldham Central","Oldham King Street","Oldham Mumps","Shaw and Crompton","South Chadderton","Westwood","Greenfield","Mills Hill"], 
    "Rochdale": ["Kingsway Business Park","Milnrow","Newbold","Newhey","Rochdale Railway Station","Rochdale Town Centre","Castleton","Littleborough","Rochdale","Smithy Bridge"], 
    "Salford": ["Anchorage","Broadway","Eccles","Exchange Quay","Harbour City","Ladywell","Langworthy","MediaCityUK","Salford Quays","Weaste","Clifton","Irlam","Moorside","Patricroft","Salford Central","Salford Crescent","Swinton","Walkden", "Glazebrook"], 
    "Stockport": ["Bramhall","Bredbury","Brinnington","Cheadle Hulme","Davenport","Gatley","Hazel Grove","Heald Green","Heaton Chapel","Marple","Middlewood","Reddish North","Romiley","Rose Hill Marple","Stockport","Strines","Woodley","Woodsmoor"], 
    "Tameside": ["Ashton Moss","Ashton-under-Lyne","Ashton West","Audenshaw","Cemetery Road","Droylsden","Edge Lane","Broadbottom","Fairfield","Flowery Field","Godley","Guide Bridge","Hattersley","Hyde Central","Hyde North","Mossley","Newton for Hyde","Stalybridge", "Glossop", "Hadfield", "Dinting"], 
    "Trafford": ["Altrincham","Barton Dock Road","Brooklands","Dane Road","Firswood","Imperial War Museum","Navigation Road","Old Trafford","Parkway","Pomona","Sale","Sale Water Park","Stretford","The Trafford Centre","Timperley","Trafford Bar","Village","Wharfside","Chassen Road","Flixton","Hale","Humphrey Park","Trafford Park","Urmston"], 
    "Wigan": ["Atherton","Bryn","Daisy Hill","Gathurst","Hag Fold","Hindley","Ince","Orrell","Pemberton","Wigan North Western","Wigan Wallgate", "Appley Bridge"] 
};

export const zoneStops = { 
    "1": ["Cornbrook", "Deansgate-Castlefield", "Exchange Square", "Market Street", "New Islington", "Piccadilly", "Piccadilly Gardens", "Shudehill", "St. Peter's Square", "Victoria", "Deansgate", "Manchester Oxford Road", "Manchester Piccadilly", "Manchester Victoria"], 
    "2": ["Abraham Moss", "Anchorage", "Barton Dock Road", "Bowker Vale", "Broadway", "Cornbrook", "Crumpsall", "Edge Lane", "Etihad Campus", "Exchange Quay", "Firswood", "Harbour City", "Holt Town", "Imperial War Museum", "Ladywell", "Langworthy", "MediaCityUK", "Monsall", "Newton Heath and Moston", "Old Trafford", "Parkway", "Pomona", "Queens Road", "Salford Quays", "St Werburgh's Road", "Stretford", "The Trafford Centre", "Trafford Bar", "Velopark", "Village", "Weaste", "Wharfside", "Salford Central", "Salford Crescent", "Ardwick", "Ashburys", "Gorton", "Belle Vue", "Ryder Brow", "Levenshulme", "Trafford Park", "Eccles"], 
    "3": ["Ashton Moss", "Ashton West", "Ashton-under-Lyne", "Audenshaw", "Baguley", "Barlow Moor Road", "Besses o' th' Barn", "Bowker Vale", "Brooklands", "Burton Road", "Cemetery Road", "Chorlton", "Clayton Hall", "Derker", "Didsbury Village", "Droylsden", "East Didsbury", "Edge Lane", "Failsworth", "Freehold", "Heaton Park", "Hollinwood", "Martinscroft", "Moor Road", "Newton Heath and Moston", "Northern Moor", "Oldham Central", "Oldham King Street", "Oldham Mumps", "Prestwich", "Roundthorn", "Sale", "Sale Water Park", "South Chadderton", "St Werburgh's Road", "Stretford", "West Didsbury", "Westwood", "Whitefield", "Withington", "Wythenshawe Park", "Moston", "Ashton-under-Lyne", "Fairfield", "Guide Bridge", "Hyde North", "Flowery Field", "Denton", "Hyde Central", "Reddish North", "Reddish South", "Brinnington", "Woodley", "Bredbury", "Heaton Chapel", "Mauldeth Road", "Burnage", "East Didsbury", "Urmston", "Humphrey Park", "Patricroft", "Moorside", "Swinton", "Clifton"], 
    "4": ["Manchester Airport", "Altrincham", "Benchill", "Brooklands", "Bury", "Crossacres", "Derker", "Kingsway Business Park", "Martinscroft", "Milnrow", "Navigation Road", "Newbold", "Newhey", "Peel Hall", "Radcliffe", "Robinswood Road", "Rochdale Railway Station", "Rochdale Town Centre", "Roundthorn", "Shadowmoss", "Shaw and Crompton", "Timperley", "Whitefield", "Wythenshawe Town Centre"] 
};

export const blacklistedStops = ["Lakeside", "Whitegate", "Tram Museum", "Middleton Road"];